### ISSUE TITLE
how to use your pre_trained model to make image foggy in colab code 

### ISSUE THREAD

**Issue by mzalaki00** [ghaiszaher/Foggy-CycleGAN#6]
Hi
Thanks for your interesting work.

you put model generator_clear2fog.h5 in drive.google but how to use this model or weight in Testing Custom images part of your 
colab code ???

**Comment by ghaiszaher** [comment]
@mzalaki00 I adjusted the notebook, simply run everything until before the training section, upload a PNG image to `custom-images/input` and run either "Testing Custom images - Plot all Results" or "Testing Single Custom Image Output"

**Comment by ghaiszaher** [comment]
I have also added another notebook to make it easier to test the latest model version: https://github.com/ghaiszaher/Foggy-CycleGAN?tab=readme-ov-file#2024-11-17-rev1-000-test-notebook-

https://colab.research.google.com/github/ghaiszaher/Foggy-CycleGAN/blob/master/2024-11-17-rev1-000-test.ipynb
